/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Mapa.glb -o src/Mapa.jsx 
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, MeshCollider } from '@react-three/rapier'

const MAP_URL = "https://pub-9696cc5ff3e74f1398157138d0c7d88a.r2.dev/Mapa.glb"

export function Model(props) {
  const { nodes, materials } = useGLTF(MAP_URL)
  useEffect(() => {
  const glassMaterials = [
    materials['Vidro.001'],
    materials['Vidro.002'],
  ]

  glassMaterials.forEach((material) => {
    if (!material) return

    material.transparent = true
    material.opacity = 0
    material.depthWrite = false
    material.needsUpdate = true
  })
}, [materials])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ArvoreMorta02.geometry} material={materials.ArvoreSeca} position={[368.346, 0.357, -0.397]} rotation={[0, -0.716, 0]} scale={0.061} />
      <group position={[367.024, 0.101, -1.068]} scale={0.076}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.AguaPoco} />
      </group>
      <mesh geometry={nodes.Node002.geometry} material={materials['mat9.001']} position={[367.117, 0.045, 0.278]} rotation={[0, 0.416, 0]} scale={0.842} />
      <mesh geometry={nodes.Node003.geometry} material={materials['mat9.001']} position={[367.309, 0.045, 0.278]} rotation={[0, 0.416, 0]} scale={0.842} />
      <mesh geometry={nodes.Node005.geometry} material={materials['mat9.001']} position={[367.693, 0.045, 0.278]} rotation={[0, 0.416, 0]} scale={0.842} />
      <mesh geometry={nodes.Node006.geometry} material={materials['mat9.001']} position={[367.885, 0.045, 0.278]} rotation={[0, 0.416, 0]} scale={0.842} />
      <mesh geometry={nodes.Node008.geometry} material={materials['mat9.001']} position={[368.27, 0.045, 0.278]} rotation={[0, 0.416, 0]} scale={0.842} />
      <mesh geometry={nodes.Node012.geometry} material={materials['mat9.001']} position={[368.367, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <mesh geometry={nodes.Node013.geometry} material={materials['mat9.001']} position={[368.175, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <mesh geometry={nodes.Node014.geometry} material={materials['mat9.001']} position={[367.983, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <mesh geometry={nodes.Node015.geometry} material={materials['mat9.001']} position={[367.791, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <mesh geometry={nodes.Node016.geometry} material={materials['mat9.001']} position={[367.599, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <mesh geometry={nodes.Node017.geometry} material={materials['mat9.001']} position={[367.407, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <mesh geometry={nodes.Node018.geometry} material={materials['mat9.001']} position={[367.215, 0.045, -0.292]} rotation={[Math.PI, -0.416, Math.PI]} scale={0.842} />
      <group position={[368.624, 0.027, 0.288]} rotation={[-Math.PI / 2, 0, 0]} scale={16.541}>
        <mesh geometry={nodes.PlanterBushes_1.geometry} material={materials.wood} />
        <mesh geometry={nodes.PlanterBushes_2.geometry} material={materials.dirt} />
        <mesh geometry={nodes.PlanterBushes_3.geometry} material={materials.plant} />
      </group>
      <mesh geometry={nodes.Plano001.geometry} material={materials['tripo_mat_e72f2716-1f66-4327-9964-6965f5100714']} position={[368.591, 0.009, 0.75]} scale={[1.479, 1.479, 0.217]} />
      <group position={[366.281, 0.064, 0.868]} rotation={[-Math.PI / 2, 0, -1.56]} scale={13.016}>
        <mesh geometry={nodes.PlanterBushes003_1.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.PlanterBushes003_2.geometry} material={materials['dirt.001']} />
        <mesh geometry={nodes.PlanterBushes003_3.geometry} material={materials['plant.001']} />
      </group>
      <group position={[366.837, 0.064, 1.449]} rotation={[-Math.PI / 2, 0, -1.56]} scale={13.016}>
        <mesh geometry={nodes.PlanterBushes002_1.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.PlanterBushes002_2.geometry} material={materials['dirt.001']} />
        <mesh geometry={nodes.PlanterBushes002_3.geometry} material={materials['plant.001']} />
      </group>
      <group position={[366.837, 0.064, 0.704]} rotation={[-Math.PI / 2, 0, -1.56]} scale={13.016}>
        <mesh geometry={nodes.PlanterBushes004_1.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.PlanterBushes004_2.geometry} material={materials['dirt.001']} />
        <mesh geometry={nodes.PlanterBushes004_3.geometry} material={materials['plant.001']} />
      </group>
      <group position={[366.837, 0.064, 1.078]} rotation={[-Math.PI / 2, 0, -1.56]} scale={13.016}>
        <mesh geometry={nodes.PlanterBushes005_1.geometry} material={materials['wood.001']} />
        <mesh geometry={nodes.PlanterBushes005_2.geometry} material={materials['dirt.001']} />
        <mesh geometry={nodes.PlanterBushes005_3.geometry} material={materials['plant.001']} />
      </group>
      <mesh geometry={nodes.Sign_Left.geometry} material={materials.Brown} position={[368.901, 0.144, 0.292]} rotation={[-Math.PI, 1.496, -Math.PI]} scale={0.182} />
      <group position={[367.998, 0.053, 1.371]} rotation={[0, 1.571, 0]} scale={0.128}>
        <mesh geometry={nodes.Sign8_1.geometry} material={materials['Dark Wood']} />
        <mesh geometry={nodes.Sign8_2.geometry} material={materials['Light Wood']} />
        <mesh geometry={nodes.Sign8_3.geometry} material={materials.Herbs} />
      </group>
      <group position={[370.063, 0.053, -0.389]} rotation={[0, 1.571, 0]} scale={0.128}>
        <mesh geometry={nodes.Sign8001_1.geometry} material={materials['Dark Wood']} />
        <mesh geometry={nodes.Sign8001_2.geometry} material={materials['Light Wood']} />
        <mesh geometry={nodes.Sign8001_3.geometry} material={materials.Herbs} />
      </group>
      <group position={[368.139, 0.047, -1.008]} rotation={[0, 1.27, 0]} scale={12.774}>
        <mesh geometry={nodes.Sign8002_1.geometry} material={materials['Dark Wood']} />
        <mesh geometry={nodes.Sign8002_2.geometry} material={materials['Light Wood']} />
        <mesh geometry={nodes.Sign8002_3.geometry} material={materials.Herbs} />
      </group>
      <group position={[366.607, 0.776, 2.267]} rotation={[0, 1.571, 0]} scale={0.031}>
        <mesh geometry={nodes['Terrain_Plane001-Mesh'].geometry} material={materials['Grass.001']} />
        <mesh geometry={nodes['Terrain_Plane001-Mesh_1'].geometry} material={materials.Ground} />
        <mesh geometry={nodes['Terrain_Plane001-Mesh_2'].geometry} material={materials.Snow} />
      </group>
      <group position={[366.276, 0.703, 1.999]} scale={0.598}>
        <mesh geometry={nodes['Node-Mesh022'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh022_1'].geometry} material={materials.mat20} />
      </group>
      <mesh geometry={nodes.Node023.geometry} material={materials['mat9.001']} position={[368.777, 0.045, 1.145]} rotation={[0, 0.949, 0]} scale={0.842} />
      <mesh geometry={nodes.Node024.geometry} material={materials['mat9.001']} position={[368.779, 0.045, 0.746]} rotation={[0, 0.416, 0]} scale={0.842} />
      <mesh geometry={nodes.rocks.geometry} material={materials.mat16} position={[368.742, 0.006, 1.318]} rotation={[-Math.PI / 2, 0, 0]} scale={11.127} />
      <mesh geometry={nodes.rocks001.geometry} material={materials.mat16} position={[368.748, 0.006, 1.448]} rotation={[-Math.PI / 2, 0, 0.778]} scale={11.127} />
      <mesh geometry={nodes.rocks002.geometry} material={materials.mat16} position={[368.568, 0.006, 1.434]} rotation={[-Math.PI / 2, 0, 2.001]} scale={11.127} />
      <mesh geometry={nodes.rocks003.geometry} material={materials.mat16} position={[368.639, 0.006, 1.294]} rotation={[-Math.PI / 2, 0, 1.278]} scale={11.127} />
      <mesh geometry={nodes.rocks004.geometry} material={materials.mat16} position={[368.742, 0.006, 0.43]} rotation={[-Math.PI / 2, 0, 0]} scale={11.127} />
      <mesh geometry={nodes.rocks005.geometry} material={materials.mat16} position={[368.748, 0.006, 0.56]} rotation={[-Math.PI / 2, 0, 0.778]} scale={11.127} />
      <mesh geometry={nodes.rocks006.geometry} material={materials.mat16} position={[368.568, 0.006, 0.547]} rotation={[-Math.PI / 2, 0, 2.001]} scale={11.127} />
      <mesh geometry={nodes.rocks007.geometry} material={materials.mat16} position={[368.639, 0.006, 0.407]} rotation={[-Math.PI / 2, 0, 1.278]} scale={11.127} />
      <mesh geometry={nodes.rocks008.geometry} material={materials.mat16} position={[368.594, 0.006, 1.729]} rotation={[-Math.PI / 2, 0, 3.14]} scale={10.326} />
      <mesh geometry={nodes.rocks009.geometry} material={materials.mat16} position={[368.589, 0.006, 1.608]} rotation={[-Math.PI / 2, 0, -2.366]} scale={10.326} />
      <mesh geometry={nodes.rocks010.geometry} material={materials.mat16} position={[368.755, 0.006, 1.621]} rotation={[-Math.PI / 2, 0, -1.143]} scale={10.326} />
      <mesh geometry={nodes.rocks011.geometry} material={materials.mat16} position={[368.69, 0.006, 1.751]} rotation={[-Math.PI / 2, 0, -1.866]} scale={10.326} />
      <mesh geometry={nodes.rocks012.geometry} material={materials.mat16} position={[368.324, 0.006, 1.633]} rotation={[-Math.PI / 2, 0, 1.911]} scale={9.489} />
      <mesh geometry={nodes.rocks013.geometry} material={materials.mat16} position={[368.427, 0.006, 1.591]} rotation={[-Math.PI / 2, 0, 2.689]} scale={9.489} />
      <mesh geometry={nodes.rocks014.geometry} material={materials.mat16} position={[368.468, 0.006, 1.739]} rotation={[-Math.PI / 2, 0, -2.371]} scale={9.489} />
      <mesh geometry={nodes.rocks015.geometry} material={materials.mat16} position={[368.335, 0.006, 1.722]} rotation={[-Math.PI / 2, 0, -3.095]} scale={9.489} />
      <mesh geometry={nodes.rocks016.geometry} material={materials.mat16} position={[369.735, 0.007, 0.507]} rotation={[-Math.PI / 2, 0, 0]} scale={21.313} />
      <mesh geometry={nodes.rocks017.geometry} material={materials.mat16} position={[370.128, 0.007, 0.508]} rotation={[-Math.PI / 2, 0, -0.521]} scale={21.313} />
      <mesh geometry={nodes.rocks018.geometry} material={materials.mat16} position={[370.392, 0.007, 0.875]} rotation={[-Math.PI / 2, 0, -1.488]} scale={21.313} />
      <mesh geometry={nodes.rocks019.geometry} material={materials.mat16} position={[370.392, 0.007, 0.158]} rotation={[-Math.PI / 2, 0, -1.488]} scale={21.313} />
      <mesh geometry={nodes.rocks020.geometry} material={materials.mat16} position={[370.407, 0.007, -0.221]} rotation={[-Math.PI / 2, 0, -0.628]} scale={21.313} />
      <mesh geometry={nodes.Geo_RoseBush.geometry} material={materials.lambert5SG} position={[368.903, 0.054, 1.746]} scale={0.004} />
      <mesh geometry={nodes.Geo_RoseBush001.geometry} material={materials.lambert5SG} position={[368.202, 0.054, 1.746]} scale={0.004} />
      <mesh geometry={nodes.Geo_RoseBush002.geometry} material={materials.lambert5SG} position={[367.5, 0.054, 1.746]} scale={0.004} />
      <mesh geometry={nodes.Geo_RoseBush003.geometry} material={materials.lambert5SG} position={[366.851, 0.054, 1.746]} scale={0.004} />
      <group position={[365.087, 0.703, 0.883]}>
        <mesh geometry={nodes['Node-Mesh027'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh027_1'].geometry} material={materials.mat20} />
      </group>
      <group position={[365.087, 0.703, 0.13]}>
        <mesh geometry={nodes['Node-Mesh028'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh028_1'].geometry} material={materials.mat20} />
      </group>
      <group position={[365.088, 0.703, -0.699]}>
        <mesh geometry={nodes['Node-Mesh029'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh029_1'].geometry} material={materials.mat20} />
      </group>
      <mesh geometry={nodes['tripo_node_e2ce9a4b-142c-4b4b-bd20-73f5a6fb0a80'].geometry} material={materials['tripo_mat_e2ce9a4b-142c-4b4b-bd20-73f5a6fb0a80']} position={[370.327, 0.068, 1.305]} />
      <mesh geometry={nodes['tripo_node_e2ce9a4b-142c-4b4b-bd20-73f5a6fb0a80001'].geometry} material={materials['tripo_mat_e2ce9a4b-142c-4b4b-bd20-73f5a6fb0a80']} position={[370.314, 0.068, -0.58]} />
      <group position={[370.072, 0.049, 0.203]} scale={0.107}>
        <mesh geometry={nodes.Cart_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cart_2.geometry} material={materials.DarkWood} />
        <mesh geometry={nodes.Cart_3.geometry} material={materials.Metal} />
      </group>
      <mesh geometry={nodes['tripo_node_1b29cbc3-0f9d-4c36-b255-852b541c4136'].geometry} material={materials['tripo_mat_1b29cbc3-0f9d-4c36-b255-852b541c4136']} position={[366.994, 0.165, 2.839]} scale={0.68} />
      <group position={[365.155, 1.043, 2.776]} scale={0.859}>
        <mesh geometry={nodes['Node-Mesh030'].geometry} material={materials.mat9} />
        <mesh geometry={nodes['Node-Mesh030_1'].geometry} material={materials.mat20} />
      </group>
      <mesh geometry={nodes.Plano.geometry} material={materials['Grama.001']} position={[368.767, 0, 1.79]} scale={[6.164, 6.164, 4.87]} />
      
      <mesh geometry={nodes.ArvoreMorta02003.geometry} material={materials['ArvoreSeca.003']} position={[367.278, 0.298, -0.367]} rotation={[0, -0.716, 0]} scale={0.051} />
      <mesh geometry={nodes.ArvoreMorta02004.geometry} material={materials['ArvoreSeca.004']} position={[367.844, 0.357, -0.377]} rotation={[0, -0.716, 0]} scale={0.061} />
      <mesh geometry={nodes.ArvoreMorta02005.geometry} material={materials['ArvoreSeca.005']} position={[367.965, 0.357, 1.6]} rotation={[-Math.PI, 0.744, -Math.PI]} scale={0.061} />
      <mesh geometry={nodes.ArvoreMorta02006.geometry} material={materials['ArvoreSeca.006']} position={[368.303, 0.298, 0.378]} rotation={[-Math.PI, 0.744, -Math.PI]} scale={0.051} />
      <mesh geometry={nodes.ArvoreMorta02008.geometry} material={materials['ArvoreSeca.008']} position={[367.234, 0.357, 0.378]} rotation={[-Math.PI, 0.744, -Math.PI]} scale={0.061} />
      <group position={[369.621, 0.154, 3.608]} rotation={[2.667, -0.218, 2.113]} scale={[0.002, 0.002, 0.001]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Folhagem.003']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Espinhos.007']} />
        <points geometry={nodes.Plane011_2.geometry} material={materials['Espinhos.006']} />
      </group>
      <mesh geometry={nodes.ArvoreMorta02009.geometry} material={materials['ArvoreSeca.009']} position={[367.775, 0.357, 0.378]} rotation={[-Math.PI, 0.744, -Math.PI]} scale={0.061} />
      <group position={[368.643, 0.102, 0.285]} rotation={[-0.487, -0.542, -1.483]} scale={0.004}>
        <mesh geometry={nodes.Plane021.geometry} material={materials['Frutos.004']} />
        <mesh geometry={nodes.Plane021_1.geometry} material={materials['Espinhos.009']} />
        <mesh geometry={nodes.Plane021_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane021_3.geometry} material={materials['Frutos.005']} />
        <mesh geometry={nodes.Plane021_4.geometry} material={materials['Espinhos.011']} />
        <mesh geometry={nodes.Plane021_5.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Plane021_6.geometry} material={materials['Frutos.006']} />
        <mesh geometry={nodes.Plane021_7.geometry} material={materials['Espinhos.013']} />
        <mesh geometry={nodes.Plane021_8.geometry} material={materials['Material.020']} />
      </group>
      <group position={[368.624, 0.027, -0.288]} rotation={[-Math.PI / 2, 0, 0]} scale={16.541}>
        <mesh geometry={nodes.PlanterBushes006.geometry} material={materials['wood.002']} />
        <mesh geometry={nodes.PlanterBushes006_1.geometry} material={materials['dirt.002']} />
        <mesh geometry={nodes.PlanterBushes006_2.geometry} material={materials['plant.002']} />
      </group>
      <group position={[368.643, 0.102, -0.291]} rotation={[-0.487, -0.542, -1.483]} scale={0.004}>
        <mesh geometry={nodes.Plane025.geometry} material={materials['Frutos.007']} />
        <mesh geometry={nodes.Plane025_1.geometry} material={materials['Espinhos.015']} />
        <mesh geometry={nodes.Plane025_2.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Plane025_3.geometry} material={materials['Frutos.008']} />
        <mesh geometry={nodes.Plane025_4.geometry} material={materials['Espinhos.017']} />
        <mesh geometry={nodes.Plane025_5.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Plane025_6.geometry} material={materials['Frutos.009']} />
        <mesh geometry={nodes.Plane025_7.geometry} material={materials['Espinhos.019']} />
        <mesh geometry={nodes.Plane025_8.geometry} material={materials['Material.023']} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Cerca.001']} position={[374.623, 0.26, 1.961]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={-0.194} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Cerca.002']} position={[370.154, 0.26, -2.656]} rotation={[-Math.PI, 0.063, -Math.PI]} scale={-0.194} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Cerca.003']} position={[370.21, 0.26, 6.142]} rotation={[-Math.PI, 0.063, -Math.PI]} scale={-0.194} />
      <mesh geometry={nodes.Geo_RoseBush004.geometry} material={materials['lambert5SG.001']} position={[368.096, 0.054, 0.251]} scale={0.004} />
      <mesh geometry={nodes.Geo_RoseBush005.geometry} material={materials['lambert5SG.002']} position={[367.493, 0.054, 0.287]} scale={0.004} />
      <group position={[366.384, 0.498, 0.735]} rotation={[Math.PI / 2, 0, -1.593]} scale={0.29}>
        <mesh geometry={nodes.Empty017.geometry} material={materials['Empty.007']} />
        <mesh geometry={nodes.Empty017_1.geometry} material={materials['Empty.003']} />
        <mesh geometry={nodes.Empty017_2.geometry} material={materials['Empty.005']} />
        <lineSegments geometry={nodes.Empty017_3.geometry} material={materials['Empty.007']} />
      </group>
      <group position={[370.572, 0.105, 3.608]} rotation={[0, 0.127, 0]} scale={0.107}>
        <mesh geometry={nodes.Cart001_1.geometry} material={materials['Wood.001']} />
        <mesh geometry={nodes.Cart001_2.geometry} material={materials['DarkWood.001']} />
        <mesh geometry={nodes.Cart001_3.geometry} material={materials['Metal.001']} />
      </group>
      <group position={[370.598, 0.123, 3.564]} rotation={[-0.487, -0.542, -1.483]} scale={0.002}>
        <mesh geometry={nodes.Plane018.geometry} material={materials['Frutos.001']} />
        <mesh geometry={nodes.Plane018_1.geometry} material={materials['Espinhos.003']} />
        <mesh geometry={nodes.Plane018_2.geometry} material={materials['Material.025']} />
      </group>
      <group position={[370.529, 0.147, 3.596]} rotation={[-0.487, -0.542, -1.483]} scale={0.002}>
        <mesh geometry={nodes.Plane020.geometry} material={materials['Frutos.012']} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials['Espinhos.025']} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials['Material.028']} />
      </group>
      <group position={[370.543, 0.119, 3.563]} rotation={[-0.487, -0.542, -1.483]} scale={0.002}>
        <mesh geometry={nodes.Plane023.geometry} material={materials['Frutos.015']} />
        <mesh geometry={nodes.Plane023_1.geometry} material={materials['Espinhos.031']} />
        <mesh geometry={nodes.Plane023_2.geometry} material={materials['Material.031']} />
      </group>
      <group position={[370.588, 0.121, 3.513]} rotation={[-0.487, -0.542, -1.483]} scale={0.002}>
        <mesh geometry={nodes.Plane024.geometry} material={materials['Frutos.018']} />
        <mesh geometry={nodes.Plane024_1.geometry} material={materials['Espinhos.037']} />
        <mesh geometry={nodes.Plane024_2.geometry} material={materials['Material.034']} />
      </group>
      <group position={[370.506, 0.113, 3.598]} rotation={[-0.487, -0.542, -1.483]} scale={0.002}>
        <mesh geometry={nodes.Plane026.geometry} material={materials['Frutos.021']} />
        <mesh geometry={nodes.Plane026_1.geometry} material={materials['Espinhos.043']} />
        <mesh geometry={nodes.Plane026_2.geometry} material={materials['Material.037']} />
      </group>
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.050']} position={[369.258, -0.006, 3.275]} />
      <group position={[369.31, 0.119, 3.027]} rotation={[-Math.PI, 0.071, -Math.PI]} scale={-0.062}>
        <mesh geometry={nodes.Plane028.geometry} material={materials['Folhagem.024']} />
        <mesh geometry={nodes.Plane028_1.geometry} material={materials['Espinhos.049']} />
        <points geometry={nodes.Plane028_2.geometry} material={materials['SoloCaatinga.001']} />
      </group>
      <mesh geometry={nodes.Node001.geometry} material={materials['mat9.002']} position={[368.777, 0.067, 3.125]} rotation={[0, 0.949, 0]} scale={0.842} />
      <mesh geometry={nodes.Node004.geometry} material={materials['mat9.003']} position={[369.548, 0.067, 3.307]} rotation={[0, 0.949, 0]} scale={0.842} />
      <mesh geometry={nodes.Node007.geometry} material={materials['mat9.004']} position={[369.176, 0.067, 3.522]} rotation={[0, 0.949, 0]} scale={0.842} />
      <group position={[369.393, 0.053, 3.563]} rotation={[-0.487, -0.542, -1.483]} scale={0.003}>
        <mesh geometry={nodes.Plane029.geometry} material={materials['Frutos.025']} />
        <mesh geometry={nodes.Plane029_1.geometry} material={materials['Espinhos.051']} />
        <mesh geometry={nodes.Plane029_2.geometry} material={materials['Material.041']} />
      </group>
      <group position={[370.007, 0.052, 3.238]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={-0.033}>
        <mesh geometry={nodes.Cube046.geometry} material={materials['Cerca.004']} />
        <lineSegments geometry={nodes.Cube046_1.geometry} material={materials['Cerca.004']} />
      </group>
      <mesh geometry={nodes.Cube008.geometry} material={materials['Cerca.005']} position={[369.247, 0.053, 3.838]} rotation={[-Math.PI, 0.003, -Math.PI]} scale={-0.033} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Cerca.006']} position={[369.247, 0.053, 2.711]} rotation={[-Math.PI, 0.003, -Math.PI]} scale={-0.033} />
      <group position={[368.535, 0.052, 3.238]} rotation={[-Math.PI, 1.568, -Math.PI]} scale={-0.033}>
        <mesh geometry={nodes.Cube050.geometry} material={materials['Cerca.007']} />
        <lineSegments geometry={nodes.Cube050_1.geometry} material={materials['Cerca.007']} />
      </group>
      <group position={[369.492, 0.052, 2.919]} rotation={[-0.487, -0.542, -1.483]} scale={0.003}>
        <mesh geometry={nodes.Plane030.geometry} material={materials['Frutos.028']} />
        <mesh geometry={nodes.Plane030_1.geometry} material={materials['Espinhos.057']} />
        <mesh geometry={nodes.Plane030_2.geometry} material={materials['Material.044']} />
      </group>
      <group position={[369.034, 0.052, 3.123]} rotation={[-0.487, -0.542, -1.483]} scale={0.003}>
        <mesh geometry={nodes.Plane031.geometry} material={materials['Frutos.031']} />
        <mesh geometry={nodes.Plane031_1.geometry} material={materials['Espinhos.063']} />
        <mesh geometry={nodes.Plane031_2.geometry} material={materials['Material.047']} />
      </group>
      <group position={[369.855, 0.02, 3.46]} scale={0.003}>
        <mesh geometry={nodes.Geo_RoseBush_1007.geometry} material={materials['lambert5SG.004']} />
        <mesh geometry={nodes.Geo_RoseBush_1007_1.geometry} material={materials['lambert5SG.003']} />
        <mesh geometry={nodes.Geo_RoseBush_1007_2.geometry} material={materials['lambert5SG.005']} />
      </group>
      <group position={[369.74, 0.02, 3.12]} scale={0.003}>
        <mesh geometry={nodes.Geo_RoseBush_1009.geometry} material={materials['lambert5SG.006']} />
        <mesh geometry={nodes.Geo_RoseBush_1009_1.geometry} material={materials['lambert5SG.007']} />
        <mesh geometry={nodes.Geo_RoseBush_1009_2.geometry} material={materials['lambert5SG.008']} />
      </group>
      <group position={[369.094, 0.02, 3.377]} scale={0.003}>
        <mesh geometry={nodes.Geo_RoseBush_1010.geometry} material={materials['lambert5SG.009']} />
        <mesh geometry={nodes.Geo_RoseBush_1010_1.geometry} material={materials['lambert5SG.010']} />
        <mesh geometry={nodes.Geo_RoseBush_1010_2.geometry} material={materials['lambert5SG.011']} />
      </group>
      <group position={[368.692, 0.02, 3.377]} scale={0.003}>
        <mesh geometry={nodes.Geo_RoseBush_1011.geometry} material={materials['lambert5SG.012']} />
        <mesh geometry={nodes.Geo_RoseBush_1011_1.geometry} material={materials['lambert5SG.013']} />
        <mesh geometry={nodes.Geo_RoseBush_1011_2.geometry} material={materials['lambert5SG.014']} />
      </group>
      <mesh geometry={nodes.Node009.geometry} material={materials['mat9.005']} position={[369.166, 0.032, 2.955]} rotation={[0, 0.949, 0]} scale={0.394} />
      <group position={[369.862, 0.094, 2.802]} rotation={[-Math.PI, 0.071, -Math.PI]} scale={-0.04}>
        <mesh geometry={nodes.Plane032.geometry} material={materials['Folhagem.034']} />
        <mesh geometry={nodes.Plane032_1.geometry} material={materials['Espinhos.069']} />
        <points geometry={nodes.Plane032_2.geometry} material={materials['SoloCaatinga.005']} />
      </group>
      <group position={[368.851, 0.058, 2.883]} rotation={[0, -0.554, 0]} scale={0.037}>
        <mesh geometry={nodes.Cube051.geometry} material={materials['Vidro.001']} />
        <mesh geometry={nodes.Cube051_1.geometry} material={materials['Texto.001']} />
        <mesh geometry={nodes.Cube051_2.geometry} material={materials['Folhagem.035']} />
        <mesh geometry={nodes.Cube051_3.geometry} material={materials['Frutos.035']} />
        <mesh geometry={nodes.Cube051_4.geometry} material={materials['Espinhos.071']} />
        <lineSegments geometry={nodes.Cube051_5.geometry} material={materials['Vidro.001']} />
        <points geometry={nodes.Cube051_6.geometry} material={materials['Vidro.001']} />
      </group>
      <group position={[368.018, 0.053, 3.722]} rotation={[-Math.PI, 0.907, -Math.PI]} scale={0.128}>
        <mesh geometry={nodes.Sign8003_1.geometry} material={materials['Dark Wood.001']} />
        <mesh geometry={nodes.Sign8003_2.geometry} material={materials['Light Wood.001']} />
        <mesh geometry={nodes.Sign8003_3.geometry} material={materials['Herbs.001']} />
      </group>
    </group>
  )
}
export function ChaoCollider() {
  const { nodes, materials } = useGLTF(MAP_URL)

  return (
    <RigidBody
      type="fixed"
      colliders={false}
      position={[-0.033, 0, -0.01]}
    >
      <MeshCollider type="trimesh">
        <mesh
          geometry={nodes.Plano.geometry}
          material={materials['Grama.001']}
          scale={[6.164, 6.164, 4.87]}
        />
      </MeshCollider>
    </RigidBody>
  )
}
useGLTF.preload(MAP_URL)
